sudo: required
services:
  - docker

before_install:
  - docker build -t mallama/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mallama/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Docker-React-Beanstalk"
  env: "Docker-React-Beanstalk-env"
  bucket_name: "elasticbeanstalk-us-west-1-130656241105"
  bucket_path: "Docker-React-Beanstalk"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
